# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

FROM gcr.io/distroless/static-debian13@sha256:e2e927ec666bae08560abb3c55d0659eceabb657f56b6782ab500a9fc7f555e3
COPY --chmod=0755 dex-dev /usr/local/bin/dex-dev
COPY web /srv/dex/web
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/dex-dev"]
