# Copyright 2026 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

devMode: true
nativeIdentity:
  enabled: true
  authenticationProfile: password-only
  bridgeImage: uds-core-dev-identity:standalone
  dexImage: uds-core-dev-dex:standalone
realmAuthFlows:
  USERNAME_PASSWORD_AUTH_ENABLED: true
  OTP_ENABLED: false
  X509_AUTH_ENABLED: false
  SOCIAL_AUTH_ENABLED: false
  WEBAUTHN_ENABLED: false
  X509_MFA_ENABLED: false
