// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

// Code generated by hack/generate-api.mjs from Core CRD schemas. DO NOT EDIT.

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ClusterConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ClusterConfigSpec   `json:"spec,omitempty"`
	Status            ClusterConfigStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type ClusterConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterConfig `json:"items"`
}

type ClusterConfigSpec struct {
	Attributes *ClusterConfigAttributes `json:"attributes,omitempty"`
	Networking *ClusterConfigNetworking `json:"networking,omitempty"`
	CABundle   *ClusterConfigCABundle   `json:"caBundle,omitempty"`
	Expose     ClusterConfigExpose      `json:"expose"`
	Policy     ClusterConfigPolicy      `json:"policy"`
}

type ClusterConfigAttributes struct {
	ClusterName *string  `json:"clusterName,omitempty"`
	Tags        []string `json:"tags,omitzero"`
}

type ClusterConfigNetworking struct {
	KubeApiCIDR   *string  `json:"kubeApiCIDR,omitempty"`
	KubeNodeCIDRs []string `json:"kubeNodeCIDRs,omitzero"`
}

type ClusterConfigCABundle struct {
	Certs              *string `json:"certs,omitempty"`
	IncludeDoDCerts    *bool   `json:"includeDoDCerts,omitempty"`
	IncludePublicCerts *bool   `json:"includePublicCerts,omitempty"`
}

type ClusterConfigExpose struct {
	Domain      string  `json:"domain"`
	AdminDomain *string `json:"adminDomain,omitempty"`
}

type ClusterConfigPolicy struct {
	AllowAllNsExemptions bool `json:"allowAllNsExemptions"`
}

type ClusterConfigStatus struct {
	ObservedGeneration *int64       `json:"observedGeneration,omitempty"`
	Phase              *ConfigPhase `json:"phase,omitempty"`
}

type ConfigPhase string

const (
	ConfigPhasePending ConfigPhase = "Pending"
	ConfigPhaseReady   ConfigPhase = "Ready"
	ConfigPhaseFailed  ConfigPhase = "Failed"
)
