// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

// Code generated by hack/generate-api.mjs from Core CRD schemas. DO NOT EDIT.

package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// +genclient
// +resourceName=packages
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type UDSPackage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              Spec          `json:"spec,omitempty"`
	Status            PackageStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type UDSPackageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UDSPackage `json:"items"`
}

type Spec struct {
	Network  *Network  `json:"network,omitempty"`
	Monitor  []Monitor `json:"monitor,omitzero"`
	Sso      []Sso     `json:"sso,omitzero"`
	CABundle *CABundle `json:"caBundle,omitempty"`
}

type Network struct {
	Expose      []Expose     `json:"expose,omitzero"`
	Allow       []Allow      `json:"allow,omitzero"`
	ServiceMesh *ServiceMesh `json:"serviceMesh,omitempty"`
}

type Expose struct {
	Description  *string           `json:"description,omitempty"`
	Protocol     *ExposeProtocol   `json:"protocol,omitempty"`
	Host         *string           `json:"host,omitempty"`
	Gateway      *string           `json:"gateway,omitempty"`
	Domain       *string           `json:"domain,omitempty"`
	Service      *string           `json:"service,omitempty"`
	Port         *float64          `json:"port,omitempty"`
	Selector     map[string]string `json:"selector,omitzero"`
	TargetPort   *float64          `json:"targetPort,omitempty"`
	AdvancedHTTP *AdvancedHTTP     `json:"advancedHTTP,omitempty"`
	Match        []ExposeMatch     `json:"match,omitzero"`
	PodLabels    map[string]string `json:"podLabels,omitzero"`
	Uptime       *Uptime           `json:"uptime,omitempty"`
	Annotations  map[string]string `json:"annotations,omitzero"`
}

type AdvancedHTTP struct {
	CorsPolicy     *CorsPolicy         `json:"corsPolicy,omitempty"`
	DirectResponse *DirectResponse     `json:"directResponse,omitempty"`
	Headers        *Headers            `json:"headers,omitempty"`
	Match          []AdvancedHTTPMatch `json:"match,omitzero"`
	Redirect       *Redirect           `json:"redirect,omitempty"`
	Retries        *Retries            `json:"retries,omitempty"`
	Rewrite        *Rewrite            `json:"rewrite,omitempty"`
	Timeout        *string             `json:"timeout,omitempty"`
}

type CorsPolicy struct {
	AllowCredentials    *bool                `json:"allowCredentials,omitempty"`
	AllowHeaders        []string             `json:"allowHeaders,omitzero"`
	AllowMethods        []string             `json:"allowMethods,omitzero"`
	AllowOrigin         []string             `json:"allowOrigin,omitzero"`
	AllowOrigins        []AllowOrigin        `json:"allowOrigins,omitzero"`
	ExposeHeaders       []string             `json:"exposeHeaders,omitzero"`
	MaxAge              *string              `json:"maxAge,omitempty"`
	UnmatchedPreflights *UnmatchedPreflights `json:"unmatchedPreflights,omitempty"`
}

type AllowOrigin struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	Regex  *string `json:"regex,omitempty"`
}

type DirectResponse struct {
	Body   *Body `json:"body,omitempty"`
	Status int64 `json:"status"`
}

type Body struct {
	Bytes  *string `json:"bytes,omitempty"`
	String *string `json:"string,omitempty"`
}

type Headers struct {
	Request  *HeaderOp `json:"request,omitempty"`
	Response *HeaderOp `json:"response,omitempty"`
}

type HeaderOp struct {
	Add    map[string]string `json:"add,omitzero"`
	Remove []string          `json:"remove,omitzero"`
	Set    map[string]string `json:"set,omitzero"`
}

type AdvancedHTTPMatch struct {
	IgnoreURICase *bool                  `json:"ignoreUriCase,omitempty"`
	Method        *StringMatch           `json:"method,omitempty"`
	Name          *string                `json:"name,omitempty"`
	QueryParams   map[string]StringMatch `json:"queryParams,omitzero"`
	URI           *StringMatch           `json:"uri,omitempty"`
}

type StringMatch struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
	Regex  *string `json:"regex,omitempty"`
}

type Redirect struct {
	Authority    *string     `json:"authority,omitempty"`
	DerivePort   *DerivePort `json:"derivePort,omitempty"`
	Port         *int64      `json:"port,omitempty"`
	RedirectCode *int64      `json:"redirectCode,omitempty"`
	Scheme       *string     `json:"scheme,omitempty"`
	URI          *string     `json:"uri,omitempty"`
}

type Retries struct {
	Attempts                 *int64  `json:"attempts,omitempty"`
	Backoff                  *string `json:"backoff,omitempty"`
	PerTryTimeout            *string `json:"perTryTimeout,omitempty"`
	RetryIgnorePreviousHosts *bool   `json:"retryIgnorePreviousHosts,omitempty"`
	RetryOn                  *string `json:"retryOn,omitempty"`
	RetryRemoteLocalities    *bool   `json:"retryRemoteLocalities,omitempty"`
}

type Rewrite struct {
	Authority       *string          `json:"authority,omitempty"`
	URI             *string          `json:"uri,omitempty"`
	URIRegexRewrite *URIRegexRewrite `json:"uriRegexRewrite,omitempty"`
}

type URIRegexRewrite struct {
	Match   *string `json:"match,omitempty"`
	Rewrite *string `json:"rewrite,omitempty"`
}

type ExposeMatch struct {
	IgnoreURICase *bool                  `json:"ignoreUriCase,omitempty"`
	Method        *StringMatch           `json:"method,omitempty"`
	Name          *string                `json:"name,omitempty"`
	QueryParams   map[string]StringMatch `json:"queryParams,omitzero"`
	URI           *StringMatch           `json:"uri,omitempty"`
}

type Uptime struct {
	Checks *Checks `json:"checks,omitempty"`
}

type Checks struct {
	Paths []string `json:"paths"`
}

type Allow struct {
	Labels               map[string]string `json:"labels,omitzero"`
	Description          *string           `json:"description,omitempty"`
	Direction            Direction         `json:"direction"`
	Selector             map[string]string `json:"selector,omitzero"`
	RemoteNamespace      *string           `json:"remoteNamespace,omitempty"`
	RemoteSelector       map[string]string `json:"remoteSelector,omitzero"`
	RemoteGenerated      *RemoteGenerated  `json:"remoteGenerated,omitempty"`
	RemoteCIDR           *string           `json:"remoteCidr,omitempty"`
	RemoteHost           *string           `json:"remoteHost,omitempty"`
	RemoteProtocol       *RemoteProtocol   `json:"remoteProtocol,omitempty"`
	Port                 *float64          `json:"port,omitempty"`
	Ports                []float64         `json:"ports,omitzero"`
	RemoteServiceAccount *string           `json:"remoteServiceAccount,omitempty"`
	ServiceAccount       *string           `json:"serviceAccount,omitempty"`
	PodLabels            map[string]string `json:"podLabels,omitzero"`
	RemotePodLabels      map[string]string `json:"remotePodLabels,omitzero"`
}

type ServiceMesh struct {
	Mode *Mode `json:"mode,omitempty"`
}

type Monitor struct {
	Description            *string                 `json:"description,omitempty"`
	PortName               string                  `json:"portName"`
	TargetPort             float64                 `json:"targetPort"`
	Selector               map[string]string       `json:"selector"`
	PodSelector            map[string]string       `json:"podSelector,omitzero"`
	Path                   *string                 `json:"path,omitempty"`
	Kind                   *MonitorKind            `json:"kind,omitempty"`
	FallbackScrapeProtocol *FallbackScrapeProtocol `json:"fallbackScrapeProtocol,omitempty"`
	Authorization          *Authorization          `json:"authorization,omitempty"`
}

type Authorization struct {
	Credentials Credentials `json:"credentials"`
	Type        *string     `json:"type,omitempty"`
}

type Credentials struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type Sso struct {
	EnableAuthserviceSelector map[string]string        `json:"enableAuthserviceSelector,omitzero"`
	SecretConfig              *SecretConfig            `json:"secretConfig,omitempty"`
	ClientID                  string                   `json:"clientId"`
	Secret                    *string                  `json:"secret,omitempty"`
	SecretName                *string                  `json:"secretName,omitempty"`
	SecretLabels              map[string]string        `json:"secretLabels,omitzero"`
	SecretAnnotations         map[string]string        `json:"secretAnnotations,omitzero"`
	SecretTemplate            map[string]string        `json:"secretTemplate,omitzero"`
	Name                      string                   `json:"name"`
	Description               *string                  `json:"description,omitempty"`
	BaseURL                   *string                  `json:"baseUrl,omitempty"`
	AdminURL                  *string                  `json:"adminUrl,omitempty"`
	Protocol                  *Protocol                `json:"protocol,omitempty"`
	Attributes                map[string]string        `json:"attributes,omitzero"`
	ProtocolMappers           []ProtocolMapper         `json:"protocolMappers,omitzero"`
	RootURL                   *string                  `json:"rootUrl,omitempty"`
	RedirectUris              []string                 `json:"redirectUris,omitzero"`
	WebOrigins                []string                 `json:"webOrigins,omitzero"`
	Enabled                   *bool                    `json:"enabled,omitempty"`
	AlwaysDisplayInConsole    *bool                    `json:"alwaysDisplayInConsole,omitempty"`
	FullScopeAllowed          *bool                    `json:"fullScopeAllowed,omitempty"`
	StandardFlowEnabled       *bool                    `json:"standardFlowEnabled,omitempty"`
	ServiceAccountsEnabled    *bool                    `json:"serviceAccountsEnabled,omitempty"`
	PublicClient              *bool                    `json:"publicClient,omitempty"`
	ClientAuthenticatorType   *ClientAuthenticatorType `json:"clientAuthenticatorType,omitempty"`
	DefaultClientScopes       []string                 `json:"defaultClientScopes,omitzero"`
	Groups                    *Groups                  `json:"groups,omitempty"`
}

type SecretConfig struct {
	Name        *string           `json:"name,omitempty"`
	Labels      map[string]string `json:"labels,omitzero"`
	Annotations map[string]string `json:"annotations,omitzero"`
	Template    map[string]string `json:"template,omitzero"`
}

type ProtocolMapper struct {
	Name            string            `json:"name"`
	Protocol        Protocol          `json:"protocol"`
	ProtocolMapper  string            `json:"protocolMapper"`
	ConsentRequired *bool             `json:"consentRequired,omitempty"`
	Config          map[string]string `json:"config,omitzero"`
}

type Groups struct {
	AnyOf []string `json:"anyOf,omitzero"`
}

type CABundle struct {
	ConfigMap *ConfigMap `json:"configMap,omitempty"`
}

type ConfigMap struct {
	Name        *string           `json:"name,omitempty"`
	Key         *string           `json:"key,omitempty"`
	Labels      map[string]string `json:"labels,omitzero"`
	Annotations map[string]string `json:"annotations,omitzero"`
}

type PackageStatus struct {
	ObservedGeneration       *int64              `json:"observedGeneration,omitempty"`
	Conditions               []Condition         `json:"conditions,omitzero"`
	Phase                    *Phase              `json:"phase,omitempty"`
	SsoClients               []string            `json:"ssoClients,omitzero"`
	AuthserviceClients       []AuthserviceClient `json:"authserviceClients,omitzero"`
	MeshMode                 *Mode               `json:"meshMode,omitempty"`
	Endpoints                []string            `json:"endpoints,omitzero"`
	Monitors                 []string            `json:"monitors,omitzero"`
	Probes                   []string            `json:"probes,omitzero"`
	NetworkPolicyCount       *int64              `json:"networkPolicyCount,omitempty"`
	AuthorizationPolicyCount *int64              `json:"authorizationPolicyCount,omitempty"`
	RetryAttempt             *int64              `json:"retryAttempt,omitempty"`
}

type Condition struct {
	Type               string      `json:"type"`
	Status             StatusEnum  `json:"status"`
	ObservedGeneration *int64      `json:"observedGeneration,omitempty"`
	LastTransitionTime metav1.Time `json:"lastTransitionTime"`
	Reason             string      `json:"reason"`
	Message            string      `json:"message"`
}

type AuthserviceClient struct {
	ClientID string            `json:"clientId"`
	Selector map[string]string `json:"selector,omitzero"`
}

type ExposeProtocol string

const (
	ExposeHTTP ExposeProtocol = "HTTP"
	ExposeUDP  ExposeProtocol = "UDP"
)

type UnmatchedPreflights string

const (
	Unspecified UnmatchedPreflights = "UNSPECIFIED"
	Forward     UnmatchedPreflights = "FORWARD"
	Ignore      UnmatchedPreflights = "IGNORE"
)

type DerivePort string

const (
	FromProtocolDefault DerivePort = "FROM_PROTOCOL_DEFAULT"
	FromRequestPort     DerivePort = "FROM_REQUEST_PORT"
)

type Direction string

const (
	Ingress Direction = "Ingress"
	Egress  Direction = "Egress"
)

type RemoteGenerated string

const (
	KubeAPI        RemoteGenerated = "KubeAPI"
	KubeNodes      RemoteGenerated = "KubeNodes"
	IntraNamespace RemoteGenerated = "IntraNamespace"
	CloudMetadata  RemoteGenerated = "CloudMetadata"
	Anywhere       RemoteGenerated = "Anywhere"
)

type RemoteProtocol string

const (
	TLS               RemoteProtocol = "TLS"
	HTTP              RemoteProtocol = "HTTP"
	RemoteProtocolTCP RemoteProtocol = "TCP"
	RemoteProtocolUDP RemoteProtocol = "UDP"
)

type Mode string

const (
	Ambient Mode = "ambient"
	Sidecar Mode = "sidecar"
)

type MonitorKind string

const (
	PodMonitor     MonitorKind = "PodMonitor"
	ServiceMonitor MonitorKind = "ServiceMonitor"
)

type FallbackScrapeProtocol string

const (
	OpenMetricsText001 FallbackScrapeProtocol = "OpenMetricsText0.0.1"
	OpenMetricsText100 FallbackScrapeProtocol = "OpenMetricsText1.0.0"
	PrometheusProto    FallbackScrapeProtocol = "PrometheusProto"
	PrometheusText004  FallbackScrapeProtocol = "PrometheusText0.0.4"
	PrometheusText100  FallbackScrapeProtocol = "PrometheusText1.0.0"
)

type Protocol string

const (
	OpenidConnect Protocol = "openid-connect"
	Saml          Protocol = "saml"
)

type ClientAuthenticatorType string

const (
	ClientSecret ClientAuthenticatorType = "client-secret"
	ClientJwt    ClientAuthenticatorType = "client-jwt"
)

type StatusEnum string

const (
	ConditionTrue    StatusEnum = "True"
	ConditionFalse   StatusEnum = "False"
	ConditionUnknown StatusEnum = "Unknown"
)

type Phase string

const (
	PhasePending       Phase = "Pending"
	PhaseReady         Phase = "Ready"
	PhaseFailed        Phase = "Failed"
	PhaseRetrying      Phase = "Retrying"
	PhaseRemoving      Phase = "Removing"
	PhaseRemovalFailed Phase = "RemovalFailed"
)
