// Copyright 2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial
// Generate API source from the same CRD schemas used by the TypeScript operator.
// api-layout.json supplies stable public Go names; it contains no field schema.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import yaml from 'js-yaml';

const root = path.resolve(import.meta.dirname, '../../..');
const layout = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, 'api-layout.json')));
const header = '// Copyright 2026 Defense Unicorns\n// SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial\n\n// Code generated by hack/generate-api.mjs from Core CRD schemas. DO NOT EDIT.\n\npackage v1alpha1\n\nimport metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"\n\n';
const goName = value => value.replace(/(^|[-_])([a-z])/g, (_, __, c) => c.toUpperCase()).replace(/([a-z])(?:Id|Url|Uri|Http|Cid[rR])(?=$|[A-Z])/g, m => m[0] + m.slice(1).toUpperCase());

for (const [kind, file, plural, rootType, specType, statusType] of [
 ['Package', 'package', 'packages', 'UDSPackage', 'Spec', 'PackageStatus'],
 ['ClusterConfig', 'clusterconfig', 'clusterconfig', 'ClusterConfig', 'ClusterConfigSpec', 'ClusterConfigStatus'],
]) {
 const crd = yaml.load(fs.readFileSync(path.join(root, `src/pepr/uds-cluster-crds/templates/${plural}.uds.dev.yaml`), 'utf8'));
 const schema = crd.spec.versions.find(v => v.name === 'v1alpha1').schema.openAPIV3Schema;
 const hints = layout[file];
 const structs = new Map(); const enums = new Map();
 function typeOf(node, hint, name) {
  if (node.type === 'array') { return '[]' + typeOf(node.items, hint?.replace(/^\[\]/,''), name); }
  if (node.type === 'object') {
   if (!node.properties) { return 'map[string]' + typeOf(node.additionalProperties === true ? {type:'string'} : node.additionalProperties || {type:'string'}, hint?.replace(/^map\[string\]/,''), name + 'Value'); }
   const type = hint?.replace(/^\*/,'') || name;
   if (!structs.has(type)) {
    structs.set(type, []);
    const fields = [];
    for (const [key, child] of Object.entries(node.properties)) {
     const field = hints.fields[type]?.[key];
     let childHint = field?.type;
     // New current-schema fields receive semantic names without changing old enum names.
     if (type === 'Expose' && key === 'protocol') childHint = '*ExposeProtocol';
     let childType = typeOf(child, childHint, goName(key));
     const required = node.required?.includes(key);
     if (!required && !childType.startsWith('[]') && !childType.startsWith('map[')) childType = '*' + childType;
     const tag = `${key}${required ? '' : (childType.startsWith('[]') || childType.startsWith('map[') ? ',omitzero' : ',omitempty')}`;
     fields.push(`\t${field?.name || goName(key)} ${childType} \x60json:"${tag}"\x60`);
    }
    structs.set(type, fields);
   }
   return type;
  }
  if (node.type === 'string') {
   const type = hint?.replace(/^\*/, '');
   if (type === 'metav1.Time' || node.format === 'date-time') return 'metav1.Time';
   if (node.enum && type && type !== 'string') { enums.set(type, node.enum); return type; }
   return 'string';
  }
  if (node.type === 'boolean') return 'bool';
  if (node.type === 'integer') return 'int64';
  if (node.type === 'number') return 'float64';
  throw new Error(`Unsupported schema type ${node.type} at ${name}`);
 }
 typeOf(schema.properties.spec, specType, specType);
 typeOf(schema.properties.status, statusType, statusType);
 let source = header + '// +genclient\n';
 source += file === 'clusterconfig' ? '// +genclient:nonNamespaced\n' : '// +resourceName=packages\n';
 source += '// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n';
 source += `type ${rootType} struct {\n\tmetav1.TypeMeta \x60json:",inline"\x60\n\tmetav1.ObjectMeta \x60json:"metadata,omitempty"\x60\n\tSpec ${specType} \x60json:"spec,omitempty"\x60\n\tStatus ${statusType} \x60json:"status,omitempty"\x60\n}\n\n`;
 source += `// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\ntype ${rootType}List struct {\n\tmetav1.TypeMeta \x60json:",inline"\x60\n\tmetav1.ListMeta \x60json:"metadata,omitempty"\x60\n\tItems []${rootType} \x60json:"items"\x60\n}\n\n`;
 for (const [name, fields] of structs) source += `type ${name} struct {\n${fields.join('\n')}\n}\n\n`;
 for (const [name, values] of enums) {
  source += `type ${name} string\n\nconst (\n`;
  for (const value of values) {
   const constant = hints.enums[name]?.[value] || (name === 'ExposeProtocol' ? `Expose${value}` : name + goName(value));
   source += `\t${constant} ${name} = ${JSON.stringify(value)}\n`;
  }
  source += ')\n\n';
 }
 const output = path.join(root, `src/go-controller/api/uds/v1alpha1/${file}.go`);
 fs.writeFileSync(output, source);
 execFileSync(process.env.GOFMT || 'gofmt', ['-w', output]);
}
