// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterConfigExpansion interface{}

type UDSPackageExpansion interface{}
