// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterConfigLister helps list ClusterConfig.
// All objects returned here must be treated as read-only.
type ClusterConfigLister interface {
	// List lists all ClusterConfig in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*udsv1alpha1.ClusterConfig, err error)
	// Get retrieves the ClusterConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*udsv1alpha1.ClusterConfig, error)
	ClusterConfigListerExpansion
}

// clusterConfigLister implements the ClusterConfigLister interface.
type clusterConfigLister struct {
	listers.ResourceIndexer[*udsv1alpha1.ClusterConfig]
}

// NewClusterConfigLister returns a new ClusterConfigLister.
func NewClusterConfigLister(indexer cache.Indexer) ClusterConfigLister {
	return &clusterConfigLister{listers.New[*udsv1alpha1.ClusterConfig](indexer, udsv1alpha1.Resource("clusterconfig"))}
}
