// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AdvancedHTTPMatchApplyConfiguration represents a declarative configuration of the AdvancedHTTPMatch type for use
// with apply.
type AdvancedHTTPMatchApplyConfiguration struct {
	IgnoreURICase *bool                                    `json:"ignoreUriCase,omitempty"`
	Method        *StringMatchApplyConfiguration           `json:"method,omitempty"`
	Name          *string                                  `json:"name,omitempty"`
	QueryParams   map[string]StringMatchApplyConfiguration `json:"queryParams,omitempty"`
	URI           *StringMatchApplyConfiguration           `json:"uri,omitempty"`
}

// AdvancedHTTPMatchApplyConfiguration constructs a declarative configuration of the AdvancedHTTPMatch type for use with
// apply.
func AdvancedHTTPMatch() *AdvancedHTTPMatchApplyConfiguration {
	return &AdvancedHTTPMatchApplyConfiguration{}
}

// WithIgnoreURICase sets the IgnoreURICase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IgnoreURICase field is set to the value of the last call.
func (b *AdvancedHTTPMatchApplyConfiguration) WithIgnoreURICase(value bool) *AdvancedHTTPMatchApplyConfiguration {
	b.IgnoreURICase = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *AdvancedHTTPMatchApplyConfiguration) WithMethod(value *StringMatchApplyConfiguration) *AdvancedHTTPMatchApplyConfiguration {
	b.Method = value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AdvancedHTTPMatchApplyConfiguration) WithName(value string) *AdvancedHTTPMatchApplyConfiguration {
	b.Name = &value
	return b
}

// WithQueryParams puts the entries into the QueryParams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the QueryParams field,
// overwriting an existing map entries in QueryParams field with the same key.
func (b *AdvancedHTTPMatchApplyConfiguration) WithQueryParams(entries map[string]StringMatchApplyConfiguration) *AdvancedHTTPMatchApplyConfiguration {
	if b.QueryParams == nil && len(entries) > 0 {
		b.QueryParams = make(map[string]StringMatchApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.QueryParams[k] = v
	}
	return b
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *AdvancedHTTPMatchApplyConfiguration) WithURI(value *StringMatchApplyConfiguration) *AdvancedHTTPMatchApplyConfiguration {
	b.URI = value
	return b
}
