// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AdvancedHTTPApplyConfiguration represents a declarative configuration of the AdvancedHTTP type for use
// with apply.
type AdvancedHTTPApplyConfiguration struct {
	CorsPolicy     *CorsPolicyApplyConfiguration         `json:"corsPolicy,omitempty"`
	DirectResponse *DirectResponseApplyConfiguration     `json:"directResponse,omitempty"`
	Headers        *HeadersApplyConfiguration            `json:"headers,omitempty"`
	Match          []AdvancedHTTPMatchApplyConfiguration `json:"match,omitempty"`
	Redirect       *RedirectApplyConfiguration           `json:"redirect,omitempty"`
	Retries        *RetriesApplyConfiguration            `json:"retries,omitempty"`
	Rewrite        *RewriteApplyConfiguration            `json:"rewrite,omitempty"`
	Timeout        *string                               `json:"timeout,omitempty"`
}

// AdvancedHTTPApplyConfiguration constructs a declarative configuration of the AdvancedHTTP type for use with
// apply.
func AdvancedHTTP() *AdvancedHTTPApplyConfiguration {
	return &AdvancedHTTPApplyConfiguration{}
}

// WithCorsPolicy sets the CorsPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CorsPolicy field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithCorsPolicy(value *CorsPolicyApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.CorsPolicy = value
	return b
}

// WithDirectResponse sets the DirectResponse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DirectResponse field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithDirectResponse(value *DirectResponseApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.DirectResponse = value
	return b
}

// WithHeaders sets the Headers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Headers field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithHeaders(value *HeadersApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.Headers = value
	return b
}

// WithMatch adds the given value to the Match field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Match field.
func (b *AdvancedHTTPApplyConfiguration) WithMatch(values ...*AdvancedHTTPMatchApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatch")
		}
		b.Match = append(b.Match, *values[i])
	}
	return b
}

// WithRedirect sets the Redirect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redirect field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithRedirect(value *RedirectApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.Redirect = value
	return b
}

// WithRetries sets the Retries field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retries field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithRetries(value *RetriesApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.Retries = value
	return b
}

// WithRewrite sets the Rewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rewrite field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithRewrite(value *RewriteApplyConfiguration) *AdvancedHTTPApplyConfiguration {
	b.Rewrite = value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *AdvancedHTTPApplyConfiguration) WithTimeout(value string) *AdvancedHTTPApplyConfiguration {
	b.Timeout = &value
	return b
}
