// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// AllowApplyConfiguration represents a declarative configuration of the Allow type for use
// with apply.
type AllowApplyConfiguration struct {
	Labels               map[string]string            `json:"labels,omitempty"`
	Description          *string                      `json:"description,omitempty"`
	Direction            *udsv1alpha1.Direction       `json:"direction,omitempty"`
	Selector             map[string]string            `json:"selector,omitempty"`
	RemoteNamespace      *string                      `json:"remoteNamespace,omitempty"`
	RemoteSelector       map[string]string            `json:"remoteSelector,omitempty"`
	RemoteGenerated      *udsv1alpha1.RemoteGenerated `json:"remoteGenerated,omitempty"`
	RemoteCIDR           *string                      `json:"remoteCidr,omitempty"`
	RemoteHost           *string                      `json:"remoteHost,omitempty"`
	RemoteProtocol       *udsv1alpha1.RemoteProtocol  `json:"remoteProtocol,omitempty"`
	Port                 *float64                     `json:"port,omitempty"`
	Ports                []float64                    `json:"ports,omitempty"`
	RemoteServiceAccount *string                      `json:"remoteServiceAccount,omitempty"`
	ServiceAccount       *string                      `json:"serviceAccount,omitempty"`
	PodLabels            map[string]string            `json:"podLabels,omitempty"`
	RemotePodLabels      map[string]string            `json:"remotePodLabels,omitempty"`
}

// AllowApplyConfiguration constructs a declarative configuration of the Allow type for use with
// apply.
func Allow() *AllowApplyConfiguration {
	return &AllowApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *AllowApplyConfiguration) WithLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithDescription(value string) *AllowApplyConfiguration {
	b.Description = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithDirection(value udsv1alpha1.Direction) *AllowApplyConfiguration {
	b.Direction = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *AllowApplyConfiguration) WithSelector(entries map[string]string) *AllowApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithRemoteNamespace sets the RemoteNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteNamespace field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteNamespace(value string) *AllowApplyConfiguration {
	b.RemoteNamespace = &value
	return b
}

// WithRemoteSelector puts the entries into the RemoteSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RemoteSelector field,
// overwriting an existing map entries in RemoteSelector field with the same key.
func (b *AllowApplyConfiguration) WithRemoteSelector(entries map[string]string) *AllowApplyConfiguration {
	if b.RemoteSelector == nil && len(entries) > 0 {
		b.RemoteSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.RemoteSelector[k] = v
	}
	return b
}

// WithRemoteGenerated sets the RemoteGenerated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteGenerated field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteGenerated(value udsv1alpha1.RemoteGenerated) *AllowApplyConfiguration {
	b.RemoteGenerated = &value
	return b
}

// WithRemoteCIDR sets the RemoteCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteCIDR field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteCIDR(value string) *AllowApplyConfiguration {
	b.RemoteCIDR = &value
	return b
}

// WithRemoteHost sets the RemoteHost field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteHost field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteHost(value string) *AllowApplyConfiguration {
	b.RemoteHost = &value
	return b
}

// WithRemoteProtocol sets the RemoteProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteProtocol field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteProtocol(value udsv1alpha1.RemoteProtocol) *AllowApplyConfiguration {
	b.RemoteProtocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithPort(value float64) *AllowApplyConfiguration {
	b.Port = &value
	return b
}

// WithPorts adds the given value to the Ports field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Ports field.
func (b *AllowApplyConfiguration) WithPorts(values ...float64) *AllowApplyConfiguration {
	for i := range values {
		b.Ports = append(b.Ports, values[i])
	}
	return b
}

// WithRemoteServiceAccount sets the RemoteServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteServiceAccount field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithRemoteServiceAccount(value string) *AllowApplyConfiguration {
	b.RemoteServiceAccount = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *AllowApplyConfiguration) WithServiceAccount(value string) *AllowApplyConfiguration {
	b.ServiceAccount = &value
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *AllowApplyConfiguration) WithPodLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithRemotePodLabels puts the entries into the RemotePodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the RemotePodLabels field,
// overwriting an existing map entries in RemotePodLabels field with the same key.
func (b *AllowApplyConfiguration) WithRemotePodLabels(entries map[string]string) *AllowApplyConfiguration {
	if b.RemotePodLabels == nil && len(entries) > 0 {
		b.RemotePodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.RemotePodLabels[k] = v
	}
	return b
}
