// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// ClusterConfigStatusApplyConfiguration represents a declarative configuration of the ClusterConfigStatus type for use
// with apply.
type ClusterConfigStatusApplyConfiguration struct {
	ObservedGeneration *int64                   `json:"observedGeneration,omitempty"`
	Phase              *udsv1alpha1.ConfigPhase `json:"phase,omitempty"`
}

// ClusterConfigStatusApplyConfiguration constructs a declarative configuration of the ClusterConfigStatus type for use with
// apply.
func ClusterConfigStatus() *ClusterConfigStatusApplyConfiguration {
	return &ClusterConfigStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ClusterConfigStatusApplyConfiguration) WithObservedGeneration(value int64) *ClusterConfigStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ClusterConfigStatusApplyConfiguration) WithPhase(value udsv1alpha1.ConfigPhase) *ClusterConfigStatusApplyConfiguration {
	b.Phase = &value
	return b
}
