// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// CorsPolicyApplyConfiguration represents a declarative configuration of the CorsPolicy type for use
// with apply.
type CorsPolicyApplyConfiguration struct {
	AllowCredentials    *bool                            `json:"allowCredentials,omitempty"`
	AllowHeaders        []string                         `json:"allowHeaders,omitempty"`
	AllowMethods        []string                         `json:"allowMethods,omitempty"`
	AllowOrigin         []string                         `json:"allowOrigin,omitempty"`
	AllowOrigins        []AllowOriginApplyConfiguration  `json:"allowOrigins,omitempty"`
	ExposeHeaders       []string                         `json:"exposeHeaders,omitempty"`
	MaxAge              *string                          `json:"maxAge,omitempty"`
	UnmatchedPreflights *udsv1alpha1.UnmatchedPreflights `json:"unmatchedPreflights,omitempty"`
}

// CorsPolicyApplyConfiguration constructs a declarative configuration of the CorsPolicy type for use with
// apply.
func CorsPolicy() *CorsPolicyApplyConfiguration {
	return &CorsPolicyApplyConfiguration{}
}

// WithAllowCredentials sets the AllowCredentials field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowCredentials field is set to the value of the last call.
func (b *CorsPolicyApplyConfiguration) WithAllowCredentials(value bool) *CorsPolicyApplyConfiguration {
	b.AllowCredentials = &value
	return b
}

// WithAllowHeaders adds the given value to the AllowHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowHeaders field.
func (b *CorsPolicyApplyConfiguration) WithAllowHeaders(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowHeaders = append(b.AllowHeaders, values[i])
	}
	return b
}

// WithAllowMethods adds the given value to the AllowMethods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowMethods field.
func (b *CorsPolicyApplyConfiguration) WithAllowMethods(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowMethods = append(b.AllowMethods, values[i])
	}
	return b
}

// WithAllowOrigin adds the given value to the AllowOrigin field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowOrigin field.
func (b *CorsPolicyApplyConfiguration) WithAllowOrigin(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.AllowOrigin = append(b.AllowOrigin, values[i])
	}
	return b
}

// WithAllowOrigins adds the given value to the AllowOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowOrigins field.
func (b *CorsPolicyApplyConfiguration) WithAllowOrigins(values ...*AllowOriginApplyConfiguration) *CorsPolicyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowOrigins")
		}
		b.AllowOrigins = append(b.AllowOrigins, *values[i])
	}
	return b
}

// WithExposeHeaders adds the given value to the ExposeHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExposeHeaders field.
func (b *CorsPolicyApplyConfiguration) WithExposeHeaders(values ...string) *CorsPolicyApplyConfiguration {
	for i := range values {
		b.ExposeHeaders = append(b.ExposeHeaders, values[i])
	}
	return b
}

// WithMaxAge sets the MaxAge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAge field is set to the value of the last call.
func (b *CorsPolicyApplyConfiguration) WithMaxAge(value string) *CorsPolicyApplyConfiguration {
	b.MaxAge = &value
	return b
}

// WithUnmatchedPreflights sets the UnmatchedPreflights field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnmatchedPreflights field is set to the value of the last call.
func (b *CorsPolicyApplyConfiguration) WithUnmatchedPreflights(value udsv1alpha1.UnmatchedPreflights) *CorsPolicyApplyConfiguration {
	b.UnmatchedPreflights = &value
	return b
}
