// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// ExposeApplyConfiguration represents a declarative configuration of the Expose type for use
// with apply.
type ExposeApplyConfiguration struct {
	Description  *string                         `json:"description,omitempty"`
	Protocol     *udsv1alpha1.ExposeProtocol     `json:"protocol,omitempty"`
	Host         *string                         `json:"host,omitempty"`
	Gateway      *string                         `json:"gateway,omitempty"`
	Domain       *string                         `json:"domain,omitempty"`
	Service      *string                         `json:"service,omitempty"`
	Port         *float64                        `json:"port,omitempty"`
	Selector     map[string]string               `json:"selector,omitempty"`
	TargetPort   *float64                        `json:"targetPort,omitempty"`
	AdvancedHTTP *AdvancedHTTPApplyConfiguration `json:"advancedHTTP,omitempty"`
	Match        []ExposeMatchApplyConfiguration `json:"match,omitempty"`
	PodLabels    map[string]string               `json:"podLabels,omitempty"`
	Uptime       *UptimeApplyConfiguration       `json:"uptime,omitempty"`
	Annotations  map[string]string               `json:"annotations,omitempty"`
}

// ExposeApplyConfiguration constructs a declarative configuration of the Expose type for use with
// apply.
func Expose() *ExposeApplyConfiguration {
	return &ExposeApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithDescription(value string) *ExposeApplyConfiguration {
	b.Description = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithProtocol(value udsv1alpha1.ExposeProtocol) *ExposeApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithHost(value string) *ExposeApplyConfiguration {
	b.Host = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithGateway(value string) *ExposeApplyConfiguration {
	b.Gateway = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithDomain(value string) *ExposeApplyConfiguration {
	b.Domain = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithService(value string) *ExposeApplyConfiguration {
	b.Service = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithPort(value float64) *ExposeApplyConfiguration {
	b.Port = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *ExposeApplyConfiguration) WithSelector(entries map[string]string) *ExposeApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithTargetPort(value float64) *ExposeApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithAdvancedHTTP sets the AdvancedHTTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdvancedHTTP field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithAdvancedHTTP(value *AdvancedHTTPApplyConfiguration) *ExposeApplyConfiguration {
	b.AdvancedHTTP = value
	return b
}

// WithMatch adds the given value to the Match field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Match field.
func (b *ExposeApplyConfiguration) WithMatch(values ...*ExposeMatchApplyConfiguration) *ExposeApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatch")
		}
		b.Match = append(b.Match, *values[i])
	}
	return b
}

// WithPodLabels puts the entries into the PodLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodLabels field,
// overwriting an existing map entries in PodLabels field with the same key.
func (b *ExposeApplyConfiguration) WithPodLabels(entries map[string]string) *ExposeApplyConfiguration {
	if b.PodLabels == nil && len(entries) > 0 {
		b.PodLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodLabels[k] = v
	}
	return b
}

// WithUptime sets the Uptime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uptime field is set to the value of the last call.
func (b *ExposeApplyConfiguration) WithUptime(value *UptimeApplyConfiguration) *ExposeApplyConfiguration {
	b.Uptime = value
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ExposeApplyConfiguration) WithAnnotations(entries map[string]string) *ExposeApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
