// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// MonitorApplyConfiguration represents a declarative configuration of the Monitor type for use
// with apply.
type MonitorApplyConfiguration struct {
	Description            *string                             `json:"description,omitempty"`
	PortName               *string                             `json:"portName,omitempty"`
	TargetPort             *float64                            `json:"targetPort,omitempty"`
	Selector               map[string]string                   `json:"selector,omitempty"`
	PodSelector            map[string]string                   `json:"podSelector,omitempty"`
	Path                   *string                             `json:"path,omitempty"`
	Kind                   *udsv1alpha1.MonitorKind            `json:"kind,omitempty"`
	FallbackScrapeProtocol *udsv1alpha1.FallbackScrapeProtocol `json:"fallbackScrapeProtocol,omitempty"`
	Authorization          *AuthorizationApplyConfiguration    `json:"authorization,omitempty"`
}

// MonitorApplyConfiguration constructs a declarative configuration of the Monitor type for use with
// apply.
func Monitor() *MonitorApplyConfiguration {
	return &MonitorApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithDescription(value string) *MonitorApplyConfiguration {
	b.Description = &value
	return b
}

// WithPortName sets the PortName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortName field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithPortName(value string) *MonitorApplyConfiguration {
	b.PortName = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithTargetPort(value float64) *MonitorApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *MonitorApplyConfiguration) WithSelector(entries map[string]string) *MonitorApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}

// WithPodSelector puts the entries into the PodSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the PodSelector field,
// overwriting an existing map entries in PodSelector field with the same key.
func (b *MonitorApplyConfiguration) WithPodSelector(entries map[string]string) *MonitorApplyConfiguration {
	if b.PodSelector == nil && len(entries) > 0 {
		b.PodSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.PodSelector[k] = v
	}
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithPath(value string) *MonitorApplyConfiguration {
	b.Path = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithKind(value udsv1alpha1.MonitorKind) *MonitorApplyConfiguration {
	b.Kind = &value
	return b
}

// WithFallbackScrapeProtocol sets the FallbackScrapeProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FallbackScrapeProtocol field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithFallbackScrapeProtocol(value udsv1alpha1.FallbackScrapeProtocol) *MonitorApplyConfiguration {
	b.FallbackScrapeProtocol = &value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *MonitorApplyConfiguration) WithAuthorization(value *AuthorizationApplyConfiguration) *MonitorApplyConfiguration {
	b.Authorization = value
	return b
}
