// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RetriesApplyConfiguration represents a declarative configuration of the Retries type for use
// with apply.
type RetriesApplyConfiguration struct {
	Attempts                 *int64  `json:"attempts,omitempty"`
	Backoff                  *string `json:"backoff,omitempty"`
	PerTryTimeout            *string `json:"perTryTimeout,omitempty"`
	RetryIgnorePreviousHosts *bool   `json:"retryIgnorePreviousHosts,omitempty"`
	RetryOn                  *string `json:"retryOn,omitempty"`
	RetryRemoteLocalities    *bool   `json:"retryRemoteLocalities,omitempty"`
}

// RetriesApplyConfiguration constructs a declarative configuration of the Retries type for use with
// apply.
func Retries() *RetriesApplyConfiguration {
	return &RetriesApplyConfiguration{}
}

// WithAttempts sets the Attempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempts field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithAttempts(value int64) *RetriesApplyConfiguration {
	b.Attempts = &value
	return b
}

// WithBackoff sets the Backoff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backoff field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithBackoff(value string) *RetriesApplyConfiguration {
	b.Backoff = &value
	return b
}

// WithPerTryTimeout sets the PerTryTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PerTryTimeout field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithPerTryTimeout(value string) *RetriesApplyConfiguration {
	b.PerTryTimeout = &value
	return b
}

// WithRetryIgnorePreviousHosts sets the RetryIgnorePreviousHosts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryIgnorePreviousHosts field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithRetryIgnorePreviousHosts(value bool) *RetriesApplyConfiguration {
	b.RetryIgnorePreviousHosts = &value
	return b
}

// WithRetryOn sets the RetryOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryOn field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithRetryOn(value string) *RetriesApplyConfiguration {
	b.RetryOn = &value
	return b
}

// WithRetryRemoteLocalities sets the RetryRemoteLocalities field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryRemoteLocalities field is set to the value of the last call.
func (b *RetriesApplyConfiguration) WithRetryRemoteLocalities(value bool) *RetriesApplyConfiguration {
	b.RetryRemoteLocalities = &value
	return b
}
