// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RewriteApplyConfiguration represents a declarative configuration of the Rewrite type for use
// with apply.
type RewriteApplyConfiguration struct {
	Authority       *string                            `json:"authority,omitempty"`
	URI             *string                            `json:"uri,omitempty"`
	URIRegexRewrite *URIRegexRewriteApplyConfiguration `json:"uriRegexRewrite,omitempty"`
}

// RewriteApplyConfiguration constructs a declarative configuration of the Rewrite type for use with
// apply.
func Rewrite() *RewriteApplyConfiguration {
	return &RewriteApplyConfiguration{}
}

// WithAuthority sets the Authority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authority field is set to the value of the last call.
func (b *RewriteApplyConfiguration) WithAuthority(value string) *RewriteApplyConfiguration {
	b.Authority = &value
	return b
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *RewriteApplyConfiguration) WithURI(value string) *RewriteApplyConfiguration {
	b.URI = &value
	return b
}

// WithURIRegexRewrite sets the URIRegexRewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URIRegexRewrite field is set to the value of the last call.
func (b *RewriteApplyConfiguration) WithURIRegexRewrite(value *URIRegexRewriteApplyConfiguration) *RewriteApplyConfiguration {
	b.URIRegexRewrite = value
	return b
}
