// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	udsv1alpha1 "github.com/defenseunicorns/uds-core/src/go-controller/api/uds/v1alpha1"
)

// SsoApplyConfiguration represents a declarative configuration of the Sso type for use
// with apply.
type SsoApplyConfiguration struct {
	EnableAuthserviceSelector map[string]string                    `json:"enableAuthserviceSelector,omitempty"`
	SecretConfig              *SecretConfigApplyConfiguration      `json:"secretConfig,omitempty"`
	ClientID                  *string                              `json:"clientId,omitempty"`
	Secret                    *string                              `json:"secret,omitempty"`
	SecretName                *string                              `json:"secretName,omitempty"`
	SecretLabels              map[string]string                    `json:"secretLabels,omitempty"`
	SecretAnnotations         map[string]string                    `json:"secretAnnotations,omitempty"`
	SecretTemplate            map[string]string                    `json:"secretTemplate,omitempty"`
	Name                      *string                              `json:"name,omitempty"`
	Description               *string                              `json:"description,omitempty"`
	BaseURL                   *string                              `json:"baseUrl,omitempty"`
	AdminURL                  *string                              `json:"adminUrl,omitempty"`
	Protocol                  *udsv1alpha1.Protocol                `json:"protocol,omitempty"`
	Attributes                map[string]string                    `json:"attributes,omitempty"`
	ProtocolMappers           []ProtocolMapperApplyConfiguration   `json:"protocolMappers,omitempty"`
	RootURL                   *string                              `json:"rootUrl,omitempty"`
	RedirectUris              []string                             `json:"redirectUris,omitempty"`
	WebOrigins                []string                             `json:"webOrigins,omitempty"`
	Enabled                   *bool                                `json:"enabled,omitempty"`
	AlwaysDisplayInConsole    *bool                                `json:"alwaysDisplayInConsole,omitempty"`
	FullScopeAllowed          *bool                                `json:"fullScopeAllowed,omitempty"`
	StandardFlowEnabled       *bool                                `json:"standardFlowEnabled,omitempty"`
	ServiceAccountsEnabled    *bool                                `json:"serviceAccountsEnabled,omitempty"`
	PublicClient              *bool                                `json:"publicClient,omitempty"`
	ClientAuthenticatorType   *udsv1alpha1.ClientAuthenticatorType `json:"clientAuthenticatorType,omitempty"`
	DefaultClientScopes       []string                             `json:"defaultClientScopes,omitempty"`
	Groups                    *GroupsApplyConfiguration            `json:"groups,omitempty"`
}

// SsoApplyConfiguration constructs a declarative configuration of the Sso type for use with
// apply.
func Sso() *SsoApplyConfiguration {
	return &SsoApplyConfiguration{}
}

// WithEnableAuthserviceSelector puts the entries into the EnableAuthserviceSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EnableAuthserviceSelector field,
// overwriting an existing map entries in EnableAuthserviceSelector field with the same key.
func (b *SsoApplyConfiguration) WithEnableAuthserviceSelector(entries map[string]string) *SsoApplyConfiguration {
	if b.EnableAuthserviceSelector == nil && len(entries) > 0 {
		b.EnableAuthserviceSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EnableAuthserviceSelector[k] = v
	}
	return b
}

// WithSecretConfig sets the SecretConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretConfig field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithSecretConfig(value *SecretConfigApplyConfiguration) *SsoApplyConfiguration {
	b.SecretConfig = value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithClientID(value string) *SsoApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithSecret(value string) *SsoApplyConfiguration {
	b.Secret = &value
	return b
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithSecretName(value string) *SsoApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithSecretLabels puts the entries into the SecretLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SecretLabels field,
// overwriting an existing map entries in SecretLabels field with the same key.
func (b *SsoApplyConfiguration) WithSecretLabels(entries map[string]string) *SsoApplyConfiguration {
	if b.SecretLabels == nil && len(entries) > 0 {
		b.SecretLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SecretLabels[k] = v
	}
	return b
}

// WithSecretAnnotations puts the entries into the SecretAnnotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SecretAnnotations field,
// overwriting an existing map entries in SecretAnnotations field with the same key.
func (b *SsoApplyConfiguration) WithSecretAnnotations(entries map[string]string) *SsoApplyConfiguration {
	if b.SecretAnnotations == nil && len(entries) > 0 {
		b.SecretAnnotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SecretAnnotations[k] = v
	}
	return b
}

// WithSecretTemplate puts the entries into the SecretTemplate field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the SecretTemplate field,
// overwriting an existing map entries in SecretTemplate field with the same key.
func (b *SsoApplyConfiguration) WithSecretTemplate(entries map[string]string) *SsoApplyConfiguration {
	if b.SecretTemplate == nil && len(entries) > 0 {
		b.SecretTemplate = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.SecretTemplate[k] = v
	}
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithName(value string) *SsoApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithDescription(value string) *SsoApplyConfiguration {
	b.Description = &value
	return b
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithBaseURL(value string) *SsoApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithAdminURL sets the AdminURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminURL field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithAdminURL(value string) *SsoApplyConfiguration {
	b.AdminURL = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithProtocol(value udsv1alpha1.Protocol) *SsoApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithAttributes puts the entries into the Attributes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Attributes field,
// overwriting an existing map entries in Attributes field with the same key.
func (b *SsoApplyConfiguration) WithAttributes(entries map[string]string) *SsoApplyConfiguration {
	if b.Attributes == nil && len(entries) > 0 {
		b.Attributes = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Attributes[k] = v
	}
	return b
}

// WithProtocolMappers adds the given value to the ProtocolMappers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProtocolMappers field.
func (b *SsoApplyConfiguration) WithProtocolMappers(values ...*ProtocolMapperApplyConfiguration) *SsoApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProtocolMappers")
		}
		b.ProtocolMappers = append(b.ProtocolMappers, *values[i])
	}
	return b
}

// WithRootURL sets the RootURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RootURL field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithRootURL(value string) *SsoApplyConfiguration {
	b.RootURL = &value
	return b
}

// WithRedirectUris adds the given value to the RedirectUris field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RedirectUris field.
func (b *SsoApplyConfiguration) WithRedirectUris(values ...string) *SsoApplyConfiguration {
	for i := range values {
		b.RedirectUris = append(b.RedirectUris, values[i])
	}
	return b
}

// WithWebOrigins adds the given value to the WebOrigins field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WebOrigins field.
func (b *SsoApplyConfiguration) WithWebOrigins(values ...string) *SsoApplyConfiguration {
	for i := range values {
		b.WebOrigins = append(b.WebOrigins, values[i])
	}
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithEnabled(value bool) *SsoApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithAlwaysDisplayInConsole sets the AlwaysDisplayInConsole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AlwaysDisplayInConsole field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithAlwaysDisplayInConsole(value bool) *SsoApplyConfiguration {
	b.AlwaysDisplayInConsole = &value
	return b
}

// WithFullScopeAllowed sets the FullScopeAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FullScopeAllowed field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithFullScopeAllowed(value bool) *SsoApplyConfiguration {
	b.FullScopeAllowed = &value
	return b
}

// WithStandardFlowEnabled sets the StandardFlowEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StandardFlowEnabled field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithStandardFlowEnabled(value bool) *SsoApplyConfiguration {
	b.StandardFlowEnabled = &value
	return b
}

// WithServiceAccountsEnabled sets the ServiceAccountsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountsEnabled field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithServiceAccountsEnabled(value bool) *SsoApplyConfiguration {
	b.ServiceAccountsEnabled = &value
	return b
}

// WithPublicClient sets the PublicClient field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicClient field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithPublicClient(value bool) *SsoApplyConfiguration {
	b.PublicClient = &value
	return b
}

// WithClientAuthenticatorType sets the ClientAuthenticatorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientAuthenticatorType field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithClientAuthenticatorType(value udsv1alpha1.ClientAuthenticatorType) *SsoApplyConfiguration {
	b.ClientAuthenticatorType = &value
	return b
}

// WithDefaultClientScopes adds the given value to the DefaultClientScopes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DefaultClientScopes field.
func (b *SsoApplyConfiguration) WithDefaultClientScopes(values ...string) *SsoApplyConfiguration {
	for i := range values {
		b.DefaultClientScopes = append(b.DefaultClientScopes, values[i])
	}
	return b
}

// WithGroups sets the Groups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Groups field is set to the value of the last call.
func (b *SsoApplyConfiguration) WithGroups(value *GroupsApplyConfiguration) *SsoApplyConfiguration {
	b.Groups = value
	return b
}
