// Copyright 2025-2026 Defense Unicorns
// SPDX-License-Identifier: LicenseRef-Defense-Unicorns-Commercial

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// URIRegexRewriteApplyConfiguration represents a declarative configuration of the URIRegexRewrite type for use
// with apply.
type URIRegexRewriteApplyConfiguration struct {
	Match   *string `json:"match,omitempty"`
	Rewrite *string `json:"rewrite,omitempty"`
}

// URIRegexRewriteApplyConfiguration constructs a declarative configuration of the URIRegexRewrite type for use with
// apply.
func URIRegexRewrite() *URIRegexRewriteApplyConfiguration {
	return &URIRegexRewriteApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *URIRegexRewriteApplyConfiguration) WithMatch(value string) *URIRegexRewriteApplyConfiguration {
	b.Match = &value
	return b
}

// WithRewrite sets the Rewrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rewrite field is set to the value of the last call.
func (b *URIRegexRewriteApplyConfiguration) WithRewrite(value string) *URIRegexRewriteApplyConfiguration {
	b.Rewrite = &value
	return b
}
